'Boolean Literals'
MCQ("Which of the following is the correct way to write a boolean literal representing 'True' in Python?", "True", "true", "TRUE", "'True'", "'true'", "True")
MCQ("What is the proper syntax for writing a boolean literal representing 'False' in Python?", "False", "false", "FALSE", "'False'", "'false'", "False")

'> Boolean Expressions '
MCQ("What is the result of the expression x > y if x = 10 and y = 5?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (a == b) and (c != d) if a = 5, b = 5, c = 10, and d = 5?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (x < y) or (y < z) if x = 3, y = 5, and z = 8?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression not (x == y) if x = 5 and y = 5?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (a > b) and (b > c) if a = 10, b = 7, and c = 3?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (x >= y) and (y >= z) if x = 5, y = 5, and z = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression not ((x < y) or (y < z)) if x = 10, y = 7, and z = 3?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (x != y) or (y != z) if x = 5, y = 5, and z = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (a == b) and (b == c) if a = 3, b = 3, and c = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (x > y) and (y < z) if x = 5, y = 7, and z = 10?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression not (x == y) if x = 10 and y = 5?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (a != b) or (c == d) if a = 5, b = 5, c = 10, and d = 5?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (x <= y) and (y >= z) if x = 3, y = 5, and z = 8?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (x > y) and (y == z) if x = 5 and y = 5?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (a >= b) or (b <= c) if a = 10, b = 7, and c = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression not ((x < y) and (y < z)) if x = 10, y = 7, and z = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (x != y) and (y != z) if x = 5, y = 5, and z = 3?", "True", "False", "None of these", "None", "Error", "False")
MCQ("What is the result of the expression (a == b) or (b == c) if a = 3, b = 3, and c = 3?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (x < y) or (y > z) if x = 5, y = 7, and z = 10?", "True", "False", "None of these", "None", "Error", "True")
MCQ("What is the result of the expression (a <= b) or (b >= c) if a = 3, b = 3, and c = 5?", "True", "False", "None of these", "None", "Error", "True")